GB-11 - Create tests
veranika107/symfony_book pull request #14
Opened 2023-03-31 13:51 UTC by veranika107

2023-03-31 13:53 UTC, veranika107 commented
![](https://github.trello.services/images/mini-trello-icon.png) [GB - Add more tests](https://trello.com/c/qxTKtuYx/11-gb-add-more-tests)

2023-03-31 16:07 UTC, wechka53 requested changes
Missing tests for commands + few small improvements required

2023-03-31 16:07 UTC, wechka53 commented on tests/Controller/ConferenceControllerTest.php
> +    public function testCommentSubmission(): void
conference controller -> method show has this block
try {
                    $photo->move($photoDir, $filename);
                } catch (FileException $e) {
                    print_r($e->getMessage());
                }
the test should cover this case as well

2023-04-03 09:02 UTC, veranika107 commented on config/services.yaml
> +        App\Service\SpamChecker:
As I know all services are private. Only in version 6.3 there will be no need to declare services as private for testing need https://symfony.com/doc/current/testing.html#mocking-dependencies

2023-04-03 09:05 UTC, veranika107 commented on tests/Service/ImageOptimizerTest.php
There is a test that check initial image ratio and the ratio of resized image, I think it covers this case

2023-04-03 10:15 UTC, wechka53 commented on tests/Service/ImageOptimizerTest.php
it doesn't 
<img width="481" alt="image" src="https://user-images.githubusercontent.com/12049388/229481104-ff29dea2-514c-40e7-8c62-8e3f2f2c05e4.png">
You can run phpunit with coverage to check it by yourself

2023-04-03 14:38 UTC, wechka53 commented on config/services.yaml
> +        App\Service\SpamChecker:
Indeed

2023-04-03 16:58 UTC, veranika107 commented on tests/MessageHandler/CommentMessageHandlerTest.php
> +            $commentMessageHandler($this->commentMessage);
there are no thrown exceptions in the code. There will be an error only if someone will remove "if" condition from the code. And in the test I want to catch this error and fail the test with described exception

2023-04-03 20:15 UTC, wechka53 commented on tests/MessageHandler/CommentMessageHandlerTest.php
> +            $commentMessageHandler($this->commentMessage);
We could try to do more correct way to test this case. For instance:
 1   if the comment is null, message handler will return void or null. 
 2.  $this->commentStateMachine->can() never be called, right?

2023-04-04 11:54 UTC, veranika107 commented on tests/Controller/ConferenceControllerTest.php
> +    public function testCommentSubmission(): void
Thank you for noticing, fixed

2023-04-04 11:55 UTC, veranika107 commented on tests/Service/ImageOptimizerTest.php
Thanks, I checked coverage. Now it is fully covered

2023-04-04 12:35 UTC, wechka53 approved these changes

2023-04-04 12:37 UTC, merged