Gb 16
veranika107/symfony_book pull request #15
Opened 2023-04-06 18:22 UTC by veranika107

2023-04-06 18:57 UTC, veranika107 commented
![](https://github.trello.services/images/mini-trello-icon.png) [GB - Implement social auth via google connect](https://trello.com/c/YQwg8Ukh/16-gb-implement-social-auth-via-google-connect)

2023-04-11 12:39 UTC, wechka53 requested changes

2023-04-11 12:39 UTC, wechka53 commented on src/Security/GoogleAuthenticator.php
> +        return new SelfValidatingPassport(
add try catch and re throw exception

2023-04-11 12:39 UTC, wechka53 commented on src/Controller/GoogleConnectController.php
> +    public function connectGoogle(ClientRegistry $clientRegistry)
add tests

2023-04-12 09:16 UTC, veranika107 commented on config/packages/security.yaml
> -                property: username
thank you, fixed

2023-04-12 09:17 UTC, veranika107 commented on src/Security/GoogleAuthenticator.php
> +        return new SelfValidatingPassport(
as we discussed, exceptions are thrown in other method. Sentry is added instead

2023-04-12 09:17 UTC, veranika107 commented on src/Controller/GoogleConnectController.php
> +    public function connectGoogle(ClientRegistry $clientRegistry)
done, thanks

2023-04-12 10:18 UTC, wechka53 approved these changes

2023-04-12 10:18 UTC, merged